### ISSUE TITLE
Docker stack Jupyter lab - citation manager

### ISSUE THREAD

**Issue by eliselavy** [C2DH/journal-of-digital-history-jupyter-stack#11]
- Python 
- R 

with the GitHub 's template

**Comment by eliselavy** [comment]
Tested Mac ok R image + citation manager



![Image](https://github.com/C2DH/journal-of-digital-history-jupyter-stack/assets/35602279/de7a33e2-2c90-41db-98df-32bcf03dadc1)

**Comment by eliselavy** [comment]
Tested  Windows 10 Enterprise
<img width="904" alt="image" src="https://github.com/C2DH/journal-of-digital-history-jupyter-stack/assets/35602279/b0398120-1a2c-4936-8a64-0c1865c84fd0">

Just the notebook can not be at the root of the work directory, need to be in a folder
<img width="810" alt="image" src="https://github.com/C2DH/journal-of-digital-history-jupyter-stack/assets/35602279/4b93f742-1ba3-43cc-b4d8-20abb2c5820b">

**Comment by eliselavy** [comment]
Problem Python code_prettify doesn't exist in JupyterLab , which formatter to use?
https://github.com/jupyterlab/jupyterlab/issues/4521

**Comment by eliselavy** [comment]
Go to use this: https://jupyter-docker-stacks.readthedocs.io/en/latest/using/selecting.html#jupyter-base-notebook

For other version of python 
![Screenshot 2024-04-04 at 16 12 56](https://github.com/C2DH/journal-of-digital-history-jupyter-stack/assets/35602279/2d585a9b-81fa-4f9a-b1dc-fb7cf98d9873)

https://github.com/jupyter/docker-stacks

but try to use : python3.9 
```
------
 > [dev 1/4] FROM quay.io/jupyter/base-notebook:ed2908bbb62e@sha256:6b8d61c7c79118ae150265fdd6105a947bc7aaea300922713d6bf3817470b413:
------
failed to solve: failed to register layer: write /opt/conda/lib/python3.9/site-packages/send2trash/exceptions.py: input/output error
```
> need to take from DockerHub

For specific tag look at here:
https://quay.io/repository/jupyter/base-notebook?tab=tags

`FROM quay.io/jupyter/base-notebook:python-3.11`


For version before 3.11 takes the tag on the DockerHub 

https://hub.docker.com/r/jupyter/base-notebook/tags?page=1&name=python-3.9.5


> Since 2023-10-20 our images are only pushed to Quay.io registry. Older images are available on Docker Hub, but they will no longer be updated.
> https://jupyter-docker-stacks.readthedocs.io/en/latest/

**Comment by eliselavy** [comment]
Test made with previous version of python but:

problem with the jupyterlab-citation-manager linked to JupyterLab >= 3.3



![Image](https://github.com/C2DH/journal-of-digital-history-jupyter-stack/assets/35602279/ed4d47fd-5c2c-4032-914b-127307b0b680)

But in local , the plugin works correctly


![Screenshot 2024-04-04 at 17 32 48](https://github.com/C2DH/journal-of-digital-history-jupyter-stack/assets/35602279/a20eedef-819e-4095-9b67-3a655705abc8)

**Comment by eliselavy** [comment]
Tested Windows OK
Same issue as R image , notebook not at the root of work

**Comment by eliselavy** [comment]
> @biumiamy Need to publish the image on the DockerHub in order to use it by this way
`docker-compose up
`

For the moment only this way:
For R:
`docker-compose -f docker-compose.dev.R.yml up --build`
For Python:
`docker-compose -f docker-compose.dev.yml up --build`

> [!WARNING]  
> On  windows no possibility to create a notebook at the root needs to be in a folder

**Comment by biumiamy** [comment]
testing done, everything works!

**Comment by eliselavy** [comment]
- Docker image for python - jupyterlab - jupyter lab citation manager published on DockerHub 
https://hub.docker.com/r/c2dhunilu/journal-of-digital-history-jupyter/tags

- For the R still needs to run via 

For R:
`docker-compose -f docker-compose.dev.R.yml up --build`


- The stack for jupyter notebook and cite2c is now in a dedicated branch: 
https://github.com/C2DH/journal-of-digital-history-jupyter-stack/tree/jupyter-notebook-cite2c

**Comment by eliselavy** [comment]
@biumiamy needs to realise the video

To emphasize on how to add library in:

- requirements.txt
- install.R

according to the needs of the article

**Comment by eliselavy** [comment]
Video available in the guidelines section
