### ISSUE TITLE
Problem of user with os big sur to install Docker Desktop

### ISSUE THREAD

**Issue by eliselavy** [C2DH/journal-of-digital-history-jupyter-stack#2]
<img width="814" alt="Screenshot 2022-07-21 at 18 51 15" src="https://user-images.githubusercontent.com/35602279/180269995-aa56f969-9428-4c10-9410-65db714ce249.png">

Mac with intel ship has been downloaded
https://docs.docker.com/desktop/install/mac-install/

No dmg file recognised by the system

dmg file send by google drive
Application not recognised
<img width="948" alt="Screenshot 2022-07-21 at 18 53 04" src="https://user-images.githubusercontent.com/35602279/180270337-7cad7abd-aab9-470a-90b2-5110b1e5f650.png">
<img width="951" alt="Screenshot 2022-07-21 at 18 53 27" src="https://user-images.githubusercontent.com/35602279/180270366-ed0d118c-c656-4ffa-840c-8d71cab2e403.png">

**Comment by eliselavy** [comment]
Upgrade on Monterey requested, same problem on the extenssion dmg not recognised
<img width="844" alt="Screenshot 2022-07-21 at 18 54 13" src="https://user-images.githubusercontent.com/35602279/180270479-50afa003-091b-46b5-aa75-fbbee7268518.png">

**Comment by eliselavy** [comment]
https://softwaretested.com/files/what-to-do-if-your-dmg-file-is-not-recognized-on-your-mac/#:~:text=One%20possible%20reason%20why%20macOS,you%20were%20downloading%20the%20file.

**Comment by lwieneke** [comment]
Had a look at this https://stackoverflow.com/questions/69552636/cannot-launch-docker-desktop-for-mac
So first thing: check if the application got the permission and then do either the manual startup or the cleaning
