### ISSUE TITLE
Docker image + Guideline: adding R in the docker image or explaining how to set up R after installation of the docker container.

### ISSUE THREAD

**Issue by inactinique** [C2DH/journal-of-digital-history-jupyter-stack#6]
The docker container's jupyter notebkk has no R kernel.

**Comment by eliselavy** [comment]
Look at here fro the R versioning: https://rocker-project.org/images/versioned/r-ver.html

**Comment by eliselavy** [comment]
https://github.com/rocker-org/rocker-versioned2 For R >4.0.0

https://github.com/rocker-org/rocker-versioned For R <4.0.0

**Comment by inactinique** [comment]
## My work around

Go to Docker Desktop.

In the ‘Containers’ tab, click on the triangle next to ‘journal-of-digital-history-jupyter-stack’. A new line appears: ‘jupyter-1’. Next to this line, click on the three dots, and click on ‘Open in Terminal’.

In the terminal, type `bash`

then type `apt update`

then type `apt install r-base r-base-dev`

(this will increase the size of your docker container of around 500 MB)

It will install R 4.0.4. If you need another version of R, you should find an old ‘.deb’ package corresponding to your version and install it, in Docker Desktop’s Terminal with the command dpkg -i r-base-3XX.deb (for instance).

Once the installation is done, still in the Terminal, type ‘R’. The R console is starting.

then, in the R console, type:

`install.packages('IRkernel')`

This will take a while. When it’s over, still in the R console open in Docker’s Terminal, type:

`IRkernel::installspec()`

You can quit the R console:

`q()`.

then `y`.

Go now back to your jupyter notebook server (something like localhost:8889/tree), open your notebook, go to the menu ‘Kernel’ > Change kernel > R (this line should have appeared now).

**Comment by eliselavy** [comment]
Re-use the Dockerfile made here https://github.com/rocker-org/rocker-versioned2 For R >4.0.0
This script updated according to our version notebook <= 6.2.0
https://github.com/rocker-org/rocker-versioned2/blob/master/scripts/install_jupyter.sh
Using this Dockerfile:
https://github.com/rocker-org/rocker-versioned2/blob/master/dockerfiles/binder_4.2.2.Dockerfile

Ok for JupyterLab + rstudio server
Not ok for Jupyter notebook forbidden access
![Screenshot 2023-01-10 at 15 15 57](https://user-images.githubusercontent.com/35602279/211595812-20fbf512-65e0-437d-a542-71946a576fab.png)

**Comment by eliselavy** [comment]
Use of https://github.com/rocker-org/binder/blob/master/Dockerfile
Look at here:
https://github.com/C2DH/journal-of-digital-history-jupyter-stack#for-rs-user

Wait for the feedback of the user before pushing the Docker image in https://hub.docker.com/r/c2dhunilu/journal-of-digital-history-jupyter

**Comment by eliselavy** [comment]
Look at here documentation made for user, if can be provided https://jsta.github.io/r-docker-tutorial/03-install-packages.html
