### ISSUE TITLE
JDH planning according to the Jupyter  release: Jupyter 7 released based on JupyterLab / migration cite2c

### ISSUE THREAD

**Issue by eliselavy** [C2DH/journal-of-digital-history-jupyter-stack#8]
- provide an overview of cite2c plugin in order to evaluate if we keep or not

need new development to fit to the author's requirement:

les années n’apparaissent pas dans les références bibliographiques

- plan a meeting with Denis Dillion

**Comment by eliselavy** [comment]
On the jupyter notebook to generate bibliography: [ citeproc-js license :: version 1.1 :: 2012.06.30 ] and citation style language: chicago-fullnote-bibliography.csl / **chicago-author-date.csl**

On the frontend JDH: "citation-js": "0.5.0" https://citation.js.org/

Csl used 
https://github.com/citation-style-language/styles/blob/master/apa.csl

and 
  if (citationsFromMetadata instanceof Object) {
    bibliography = **new Cite(Object.values(citationsFromMetadata))**
  }


const ArticleBilbiography = ({ articleTree }) => {
  const { t } = useTranslation()

  return (
    <Container className="mt-5">
      <Row>
        <Col md={{ span: 7, offset: 2 }}>
          <h2>{t('bibliography')}</h2>
          <div dangerouslySetInnerHTML={{
            __html: articleTree.**formatBibliograhpy()**
          }}/>
        </Col>
      </Row>
    </Container>
  )
}

**Comment by eliselavy** [comment]
Plugin cite2c for Jupyter Lab: https://github.com/krassowski/jupyterlab-citation-manager
`pip install jupyterlab-citation-manager`
In order to solve this : https://github.com/jupyterlab/jupyterlab/issues/10228
`jupyter server extension disable nbclassic`

<img width="1080" alt="File Edit View Run" src="https://user-images.githubusercontent.com/35602279/212079795-5a3c5a0b-81dd-435f-8ddb-4db754b4f4be.png">

An automatic migration is proposed from cite2c to citation manager:
<img width="520" alt="Importing cite2c citations is possible" src="https://user-images.githubusercontent.com/35602279/212079839-eea242ae-a21c-43c6-a686-63a6fab3f33b.png">
<img width="301" alt="Python 3" src="https://user-images.githubusercontent.com/35602279/212079878-a7fbad0c-1a2a-459c-b8e1-6cf91b82c7c7.png">

![Screenshot 2023-01-12 at 14 48 12](https://user-images.githubusercontent.com/35602279/212083556-a972eef3-4718-4f1c-9081-3eef96e9fff6.png)

**Comment by eliselavy** [comment]
TO DO:


Test full functionnality of the citation manager plugin and give feedback about roadmap for Jupyter Lab migration
- migration of notebook performed with cit2c
- update reference in zotero
- insert more than one same reference
- support zotero group

**Comment by eliselavy** [comment]
And also look at Jupyter Lab Desktop: https://github.com/jupyterlab/jupyterlab-desktop

**Comment by eliselavy** [comment]
Since 23 april 2023: A major upgrade to the Jupyter Notebook interface is coming with Notebook 7! This upgrade will bring a heap of new features, but will also break backwards compatibility with many classic Notebook features and customizations.

**Comment by biumiamy** [comment]
- ~talk to Andreas about budget to fix the cite2c problem externally~

**Comment by biumiamy** [comment]
Once the migration is done, we can start with this: [Make notebook code interactive#280](https://github.com/C2DH/journal-of-digital-history/issues/280)

**Comment by eliselavy** [comment]
@inactinique write article by using this extension: https://github.com/krassowski/jupyterlab-citation-manager  in JupyterLab  https://github.com/jupyterlab/jupyterlab-desktop for evaluation

**Comment by eliselavy** [comment]
Citation manager as cite2c doesn't take into account the group. References need to be at the level: My libraries

**Comment by eliselavy** [comment]
Mail to Steve Purves made to support the migration.

**Comment by eliselavy** [comment]
- Test JupyterLab app 
- Test the Jupyter Notebook Scientific Python Stack Marcelo Ochoa. jupyter docker extension 

https://www.docker.com/blog/getting-started-with-jupyterlab-as-a-docker-extension/
 https://github.com/marcelo-ochoa/jupyter-docker-extension


Test to see if easy to change kernel https://github.com/marcelo-ochoa/jupyter-docker-extension/blob/main/addR.sh

In terminal:

`docker exec -ti --user root jupyter_embedded_dd_vm /bin/sh -c "curl -s https://raw.githubusercontent.com/marcelo-ochoa/jupyter-docker-extension/main/addR.sh | bash"`


![Image](https://github.com/C2DH/journal-of-digital-history-jupyter-stack/assets/35602279/c625ffae-c616-4aa3-9473-b0dcbbc8a9ad)



![Image](https://github.com/C2DH/journal-of-digital-history-jupyter-stack/assets/35602279/b61ed3c2-aa44-4a14-895b-38e5bc5aa69b)

**Comment by eliselavy** [comment]
And install the plugin : https://github.com/krassowski/jupyterlab-citation-manager

![Screenshot 2024-02-20 at 10 43 40](https://github.com/C2DH/journal-of-digital-history-jupyter-stack/assets/35602279/29d5569f-e7bb-4ae8-8db2-862d445fc908)

**Comment by eliselavy** [comment]
Migration in automatic:
`(<cite id=\"cite2c-7748027/CNCDVWQ5\"><a href=\"#cite2c%7C7748027%2FCNCDVWQ5\">(<i>Trans-Atlantic Slave Trade - Rio de Janeiro Estimates</i>, 2023)</a></cite>)`

Bibliography : 
 formatted with html tag
